-- Starter recipes. GENERATED by scripts/build-seed.mjs from seed/recipes.json.
-- Edit the JSON and re-run the script; do not edit this file by hand.
--
-- HOW TO RUN: Supabase dashboard -> SQL Editor -> paste this whole file -> Run.
-- Run supabase/schema.sql first, and sign in to the app once so your account exists.
--
-- The SQL editor runs as a privileged role that bypasses Row Level Security, so this
-- script has to say whose recipes these are. Set owner_email to the address you signed
-- in with. It fails loudly if no such user exists rather than inserting orphan rows.
--
-- Safe to re-run: a recipe whose title you already have is skipped, not duplicated.

do $seed_do$
declare
  owner_email constant text := 'CHANGE-ME@example.com';
  owner_id    uuid;
  inserted    integer;
begin
  select id into owner_id from auth.users where lower(email) = lower(owner_email);
  if owner_id is null then
    raise exception 'No user with email %. Edit owner_email at the top of this script.', owner_email;
  end if;

  insert into public.recipes
    (user_id, title, servings, prep_minutes, cook_minutes, ingredients, steps, tags,
     allium_free, source_url, notes, rating, last_cooked)
  select
    owner_id, r.title, r.servings, r.prep_minutes, r.cook_minutes, r.ingredients,
    array(select jsonb_array_elements_text(r.steps)),
    array(select jsonb_array_elements_text(r.tags)),
    r.allium_free, r.source_url, r.notes, r.rating, r.last_cooked
  from jsonb_to_recordset($seed$
[
  {
    "title": "Pan-fried flathead with lemon-caper butter and shaved fennel",
    "servings": 2,
    "prep_minutes": 15,
    "cook_minutes": 12,
    "ingredients": [
      {
        "qty": "4",
        "unit": "",
        "item": "flathead fillets, about 150 g each, skin off"
      },
      {
        "qty": "30",
        "unit": "g",
        "item": "plain flour"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "sea salt flakes"
      },
      {
        "qty": "",
        "unit": "",
        "item": "black pepper"
      },
      {
        "qty": "30",
        "unit": "ml",
        "item": "olive oil"
      },
      {
        "qty": "40",
        "unit": "g",
        "item": "unsalted butter"
      },
      {
        "qty": "2",
        "unit": "",
        "item": "garlic cloves, thinly sliced"
      },
      {
        "qty": "15",
        "unit": "g",
        "item": "capers, drained and roughly chopped"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "lemon, zested then juiced"
      },
      {
        "qty": "15",
        "unit": "g",
        "item": "flat-leaf parsley, chopped"
      },
      {
        "qty": "1",
        "unit": "small",
        "item": "fennel bulb, shaved paper-thin (for the salad)"
      },
      {
        "qty": "20",
        "unit": "ml",
        "item": "olive oil (for the salad)"
      }
    ],
    "steps": [
      "Shave the fennel as thin as you can with a mandoline or very sharp knife. Toss with the salad oil, 10 ml of the lemon juice, a pinch of salt and the fennel fronds. Leave it while you cook; it softens slightly and is better for it.",
      "Pat the fillets very dry. Mix the flour, salt and pepper on a plate and dust the fillets lightly, shaking off the excess.",
      "Heat the oil in a large frying pan over medium-high until it shimmers. Cook the fillets 2 minutes a side, until golden and just opaque. Do two batches if the pan is crowded. Move to a warm plate.",
      "Drop the heat to medium and add the butter. When it foams, add the garlic and capers for 30 seconds, then the lemon zest and remaining juice. Swirl, take off the heat and stir through the parsley.",
      "Spoon the butter over the fish and serve with the fennel salad and boiled baby potatoes or crusty bread."
    ],
    "tags": [
      "fish",
      "seafood",
      "weeknight",
      "high-protein",
      "to-try"
    ],
    "allium_free": true,
    "source_url": null,
    "notes": "Draft, not cooked yet. Works with any thin white fillet: whiting, bream, garfish. If you caught it, rest the fillets on paper towel in the fridge for an hour first; a dry surface is what gets the colour.",
    "rating": null,
    "last_cooked": null
  },
  {
    "title": "Foil-baked bream with fennel, tomato and olives",
    "servings": 2,
    "prep_minutes": 15,
    "cook_minutes": 25,
    "ingredients": [
      {
        "qty": "2",
        "unit": "",
        "item": "whole bream, gutted and scaled, about 350 g each"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "fennel bulb, thinly sliced"
      },
      {
        "qty": "200",
        "unit": "g",
        "item": "cherry tomatoes, halved"
      },
      {
        "qty": "60",
        "unit": "g",
        "item": "pitted green olives"
      },
      {
        "qty": "2",
        "unit": "",
        "item": "garlic cloves, sliced"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "fennel seeds"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "lemon, half sliced and half juiced"
      },
      {
        "qty": "30",
        "unit": "ml",
        "item": "olive oil"
      },
      {
        "qty": "100",
        "unit": "ml",
        "item": "dry white wine"
      },
      {
        "qty": "",
        "unit": "",
        "item": "salt and black pepper"
      },
      {
        "qty": "",
        "unit": "",
        "item": "parsley or fennel fronds, to finish"
      }
    ],
    "steps": [
      "Heat the oven to 200 °C (180 °C fan).",
      "Toss the fennel, tomatoes, olives, garlic, fennel seeds, 20 ml of the oil and a pinch of salt in a bowl.",
      "Tear off two sheets of foil, each about 40 cm long. Put half the vegetables on each, slightly off-centre so the foil can fold over.",
      "Slash each fish three times on both sides, down to the bone. Season inside and out and tuck lemon slices into the cavity. Lay the fish on the vegetables, drizzle with the remaining oil and pour 50 ml wine over each.",
      "Fold the foil over and crimp the edges into sealed parcels with some headspace for steam. Put on a tray and bake 22 to 25 minutes, until the flesh flakes at the thickest part near the backbone.",
      "Open carefully; the steam is fierce. Squeeze over the lemon juice, scatter with parsley or fronds and eat from the parcel with bread for the juices."
    ],
    "tags": [
      "fish",
      "seafood",
      "oven",
      "low-effort",
      "to-try"
    ],
    "allium_free": true,
    "source_url": null,
    "notes": "Draft, not cooked yet. A bigger fish (600 g and up) needs around 35 minutes. Fillets work too: 4 fillets, 12 to 15 minutes. Snapper, trevally or Aussie salmon are good swaps.",
    "rating": null,
    "last_cooked": null
  },
  {
    "title": "Garlic and chilli calamari",
    "servings": 2,
    "prep_minutes": 10,
    "cook_minutes": 6,
    "ingredients": [
      {
        "qty": "400",
        "unit": "g",
        "item": "cleaned squid tubes"
      },
      {
        "qty": "30",
        "unit": "ml",
        "item": "olive oil"
      },
      {
        "qty": "4",
        "unit": "",
        "item": "garlic cloves, thinly sliced"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "long red chilli, sliced"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "lemon, half juiced and half in wedges"
      },
      {
        "qty": "15",
        "unit": "g",
        "item": "flat-leaf parsley, roughly chopped"
      },
      {
        "qty": "",
        "unit": "",
        "item": "sea salt flakes"
      },
      {
        "qty": "",
        "unit": "",
        "item": "crusty bread or rocket, to serve"
      }
    ],
    "steps": [
      "Pat the squid completely dry; wet squid steams and turns rubbery. Slice the tubes into 1 cm rings, or open them out, score the inside in a crosshatch and cut into strips.",
      "Get a large frying pan very hot. Add half the oil, then half the squid in a single layer. Cook 60 to 90 seconds, until it just turns opaque and curls. Tip onto a plate and repeat with the rest.",
      "Wipe out the pan, drop the heat to medium and add the remaining oil, garlic and chilli. Cook about 30 seconds until fragrant. Do not let the garlic brown.",
      "Return the squid with the lemon juice, parsley and a good pinch of salt. Toss for 15 seconds and serve at once with lemon wedges."
    ],
    "tags": [
      "seafood",
      "quick",
      "weeknight",
      "high-protein",
      "to-try"
    ],
    "allium_free": true,
    "source_url": null,
    "notes": "Draft, not cooked yet. Squid is either fast (under 2 minutes) or slow (braised 40 minutes or more). Anything in between is chewy. Works for squid caught off a pier too: clean it, then follow the same steps.",
    "rating": null,
    "last_cooked": null
  },
  {
    "title": "Fennel, carrot and celery ragù (onion-free bolognese)",
    "servings": 4,
    "prep_minutes": 20,
    "cook_minutes": 100,
    "ingredients": [
      {
        "qty": "45",
        "unit": "ml",
        "item": "olive oil, divided"
      },
      {
        "qty": "1",
        "unit": "large",
        "item": "fennel bulb, finely diced (about 250 g)"
      },
      {
        "qty": "2",
        "unit": "",
        "item": "carrots, finely diced"
      },
      {
        "qty": "2",
        "unit": "",
        "item": "celery sticks, finely diced"
      },
      {
        "qty": "4",
        "unit": "",
        "item": "garlic cloves, finely chopped"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "fennel seeds"
      },
      {
        "qty": "500",
        "unit": "g",
        "item": "beef mince"
      },
      {
        "qty": "40",
        "unit": "g",
        "item": "tomato paste"
      },
      {
        "qty": "150",
        "unit": "ml",
        "item": "dry red wine"
      },
      {
        "qty": "400",
        "unit": "g",
        "item": "tin whole peeled tomatoes, plain (not flavoured)"
      },
      {
        "qty": "250",
        "unit": "ml",
        "item": "water"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "bay leaf"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "dried oregano"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "salt, plus more to taste"
      },
      {
        "qty": "400",
        "unit": "g",
        "item": "spaghetti or tagliatelle"
      },
      {
        "qty": "",
        "unit": "",
        "item": "parmesan, to serve"
      }
    ],
    "steps": [
      "Heat 30 ml of the oil in a heavy pot over medium heat. Add the fennel, carrot, celery and a pinch of salt and cook 12 to 15 minutes, stirring, until soft, sweet and just starting to colour. This is the flavour base for everything that follows, so do not rush it.",
      "Add the garlic and fennel seeds and cook 1 minute.",
      "Push the vegetables aside, add the remaining oil, turn the heat up and add the mince in two lots. Leave it alone long enough to brown properly, about 8 minutes in total, breaking it up as it colours.",
      "Stir in the tomato paste and cook 2 minutes. Add the wine and let it bubble down by half, about 3 minutes.",
      "Add the tomatoes (crush them with the spoon), water, bay leaf, oregano and the salt. Bring to a simmer, then turn right down with the lid ajar and cook 60 to 75 minutes, stirring now and then. Add a splash of water if it catches.",
      "Taste and adjust the salt. Cook the pasta in well-salted water until 1 minute short of the packet time. Toss with the ragù and a splash of pasta water. Serve with parmesan."
    ],
    "tags": [
      "pasta",
      "batch-cook",
      "freezer-friendly",
      "family",
      "to-try"
    ],
    "allium_free": true,
    "source_url": null,
    "notes": "Draft, not cooked yet. Fennel gives the sweetness onion would, celery the savoury depth, fennel seeds the sausage-ish note. Freezes well in portions for about 3 months. Check the tinned tomatoes say tomatoes only: the flavoured ones often contain onion.",
    "rating": null,
    "last_cooked": null
  },
  {
    "title": "Lemon-oregano chicken and fennel traybake",
    "servings": 4,
    "prep_minutes": 15,
    "cook_minutes": 50,
    "ingredients": [
      {
        "qty": "8",
        "unit": "",
        "item": "bone-in, skin-on chicken thighs (about 1.2 kg)"
      },
      {
        "qty": "600",
        "unit": "g",
        "item": "baby potatoes, halved"
      },
      {
        "qty": "2",
        "unit": "",
        "item": "fennel bulbs, cut into wedges"
      },
      {
        "qty": "6",
        "unit": "",
        "item": "garlic cloves, left unpeeled"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "lemon, half sliced and half juiced"
      },
      {
        "qty": "45",
        "unit": "ml",
        "item": "olive oil"
      },
      {
        "qty": "2",
        "unit": "tsp",
        "item": "dried oregano"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "smoked paprika"
      },
      {
        "qty": "1.5",
        "unit": "tsp",
        "item": "salt, divided"
      },
      {
        "qty": "",
        "unit": "",
        "item": "black pepper"
      },
      {
        "qty": "100",
        "unit": "g",
        "item": "Kalamata olives (optional)"
      },
      {
        "qty": "",
        "unit": "",
        "item": "flat-leaf parsley, to finish"
      }
    ],
    "steps": [
      "Heat the oven to 220 °C (200 °C fan).",
      "Toss the potatoes, fennel wedges and garlic with 30 ml of the oil and half the salt on a large tray. Roast 10 minutes while you prepare the chicken.",
      "Rub the chicken with the remaining oil, oregano, paprika, remaining salt, pepper and the lemon juice.",
      "Nestle the chicken skin-side up among the vegetables and tuck in the lemon slices. Roast 35 to 40 minutes, until the skin is crisp and the thickest part reads at least 75 °C.",
      "Rest 5 minutes. Squeeze a couple of the soft garlic cloves out over everything, scatter with olives and parsley, and serve from the tray."
    ],
    "tags": [
      "chicken",
      "traybake",
      "high-protein",
      "family",
      "to-try"
    ],
    "allium_free": true,
    "source_url": null,
    "notes": "Draft, not cooked yet. One tray, almost no washing up. Skinless thigh fillets work too: roast 25 minutes and add them to the tray after the vegetables have had their 10.",
    "rating": null,
    "last_cooked": null
  },
  {
    "title": "Chilli garlic prawns with white beans",
    "servings": 2,
    "prep_minutes": 10,
    "cook_minutes": 12,
    "ingredients": [
      {
        "qty": "400",
        "unit": "g",
        "item": "raw prawns, peeled, tails on"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "smoked paprika"
      },
      {
        "qty": "30",
        "unit": "ml",
        "item": "olive oil, divided"
      },
      {
        "qty": "4",
        "unit": "",
        "item": "garlic cloves, sliced"
      },
      {
        "qty": "0.5",
        "unit": "tsp",
        "item": "chilli flakes"
      },
      {
        "qty": "150",
        "unit": "g",
        "item": "cherry tomatoes, halved"
      },
      {
        "qty": "100",
        "unit": "ml",
        "item": "dry white wine"
      },
      {
        "qty": "400",
        "unit": "g",
        "item": "tin cannellini beans, drained and rinsed"
      },
      {
        "qty": "50",
        "unit": "ml",
        "item": "water"
      },
      {
        "qty": "60",
        "unit": "g",
        "item": "baby spinach"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "lemon, juiced"
      },
      {
        "qty": "15",
        "unit": "g",
        "item": "flat-leaf parsley, chopped"
      },
      {
        "qty": "",
        "unit": "",
        "item": "salt"
      },
      {
        "qty": "",
        "unit": "",
        "item": "crusty bread, to serve"
      }
    ],
    "steps": [
      "Pat the prawns dry and toss with the paprika and a pinch of salt.",
      "Heat 15 ml of the oil in a large pan over medium-high heat. Sear the prawns 1 minute a side, until just pink. Tip them onto a plate; they will finish cooking later.",
      "Drop the heat to medium and add the remaining oil, garlic and chilli. Cook 30 seconds, then add the tomatoes for 2 minutes until they slump.",
      "Add the wine and let it bubble for 1 minute. Add the beans and water and simmer 4 minutes, crushing a few beans against the side of the pan to thicken the sauce.",
      "Return the prawns with the spinach. Cook about 1 minute, until the spinach wilts and the prawns are opaque. Finish with the lemon juice and parsley and serve with bread."
    ],
    "tags": [
      "seafood",
      "quick",
      "one-pan",
      "high-protein",
      "weeknight",
      "to-try"
    ],
    "allium_free": true,
    "source_url": null,
    "notes": "Draft, not cooked yet. About 20 minutes start to finish. Use water, not stock, for the sauce: most stock contains onion.",
    "rating": null,
    "last_cooked": null
  },
  {
    "title": "Miso-glazed salmon with sesame greens and rice",
    "servings": 2,
    "prep_minutes": 10,
    "cook_minutes": 15,
    "ingredients": [
      {
        "qty": "2",
        "unit": "",
        "item": "salmon fillets, skin on, about 160 g each"
      },
      {
        "qty": "30",
        "unit": "g",
        "item": "white miso paste"
      },
      {
        "qty": "15",
        "unit": "ml",
        "item": "mirin"
      },
      {
        "qty": "15",
        "unit": "ml",
        "item": "soy sauce, plus a splash for the greens"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "sugar"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "finely grated ginger"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "sesame oil, divided"
      },
      {
        "qty": "150",
        "unit": "g",
        "item": "jasmine rice"
      },
      {
        "qty": "300",
        "unit": "g",
        "item": "broccolini or bok choy"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "neutral oil"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "sesame seeds"
      }
    ],
    "steps": [
      "Whisk the miso, mirin, soy, sugar, ginger and half the sesame oil. Coat the salmon and leave 15 to 30 minutes. Do not go past 2 hours: the miso starts to cure the flesh.",
      "Cook the rice to the packet directions.",
      "Wipe most of the marinade off the salmon and keep it; a thin film is enough, and more than that burns. Heat the neutral oil in a non-stick pan over medium-high. Cook the salmon skin-side down 4 minutes until the skin is crisp, then flip for 2 to 3 minutes. Brush with a little of the reserved marinade in the last minute.",
      "Steam or blanch the greens 3 minutes. Toss with the remaining sesame oil, a splash of soy and the sesame seeds.",
      "Serve the salmon on the rice with the greens alongside."
    ],
    "tags": [
      "fish",
      "japanese-ish",
      "quick",
      "high-protein",
      "weeknight",
      "to-try"
    ],
    "allium_free": true,
    "source_url": null,
    "notes": "Draft, not cooked yet. Usually finished with spring onion, which is the one thing to leave off; sesame seeds and a little coriander do the job. Plain miso paste is fine, but glance at the label if it is a flavoured or instant one.",
    "rating": null,
    "last_cooked": null
  },
  {
    "title": "Onion-free shakshuka",
    "servings": 2,
    "prep_minutes": 10,
    "cook_minutes": 30,
    "ingredients": [
      {
        "qty": "30",
        "unit": "ml",
        "item": "olive oil"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "red capsicum, diced"
      },
      {
        "qty": "1",
        "unit": "small",
        "item": "fennel bulb, finely diced (about 150 g)"
      },
      {
        "qty": "3",
        "unit": "",
        "item": "garlic cloves, finely chopped"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "ground cumin"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "sweet paprika"
      },
      {
        "qty": "0.5",
        "unit": "tsp",
        "item": "ground coriander"
      },
      {
        "qty": "1",
        "unit": "pinch",
        "item": "chilli flakes"
      },
      {
        "qty": "400",
        "unit": "g",
        "item": "tin chopped tomatoes, plain (not flavoured)"
      },
      {
        "qty": "0.5",
        "unit": "tsp",
        "item": "salt"
      },
      {
        "qty": "4",
        "unit": "",
        "item": "eggs"
      },
      {
        "qty": "60",
        "unit": "g",
        "item": "feta"
      },
      {
        "qty": "",
        "unit": "",
        "item": "coriander or parsley leaves"
      },
      {
        "qty": "",
        "unit": "",
        "item": "toasted sourdough or flatbread, to serve"
      }
    ],
    "steps": [
      "Heat the oil in a wide, deep frying pan over medium. Add the fennel and capsicum and cook 8 to 10 minutes until soft and sweet. This is the flavour base.",
      "Add the garlic, cumin, paprika, coriander and chilli and stir for 1 minute.",
      "Add the tomatoes and salt. Simmer 10 minutes, until thick enough that a spoon leaves a dent.",
      "Make four wells in the sauce and crack an egg into each. Cover and cook on low 5 to 7 minutes, until the whites are set and the yolks still wobble.",
      "Crumble over the feta, add the herbs and serve straight from the pan with bread."
    ],
    "tags": [
      "breakfast",
      "brunch",
      "eggs",
      "vegetarian",
      "one-pan",
      "to-try"
    ],
    "allium_free": true,
    "source_url": null,
    "notes": "Draft, not cooked yet. Make the sauce up to 2 days ahead and just add the eggs when you want it.",
    "rating": null,
    "last_cooked": null
  },
  {
    "title": "Ginger chicken congee",
    "servings": 4,
    "prep_minutes": 10,
    "cook_minutes": 70,
    "ingredients": [
      {
        "qty": "200",
        "unit": "g",
        "item": "jasmine rice, rinsed"
      },
      {
        "qty": "1.8",
        "unit": "L",
        "item": "water, plus extra hot water if needed"
      },
      {
        "qty": "40",
        "unit": "g",
        "item": "ginger, half sliced into coins and half cut into thin matchsticks"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "salt"
      },
      {
        "qty": "500",
        "unit": "g",
        "item": "boneless chicken thighs"
      },
      {
        "qty": "20",
        "unit": "ml",
        "item": "fish sauce"
      },
      {
        "qty": "15",
        "unit": "ml",
        "item": "soy sauce"
      },
      {
        "qty": "",
        "unit": "",
        "item": "white pepper"
      },
      {
        "qty": "4",
        "unit": "",
        "item": "eggs, soft-boiled (6.5 minutes)"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "sesame oil"
      },
      {
        "qty": "",
        "unit": "",
        "item": "coriander leaves and sesame seeds, to serve"
      }
    ],
    "steps": [
      "Put the rice, water, ginger coins and salt in a large pot and bring to the boil, stirring. Turn down low with the lid ajar and simmer 30 minutes, stirring now and then so the base does not catch.",
      "Add the whole chicken thighs and simmer another 25 to 30 minutes, until the chicken is tender and the rice has broken down into a loose porridge. Add hot water if it gets too thick.",
      "Lift out the chicken, shred it with two forks and return it to the pot. Stir in the fish sauce, soy and a good shake of white pepper. Taste and adjust.",
      "Ladle into bowls and top with the ginger matchsticks, a soft-boiled egg, the sesame oil, coriander and sesame seeds."
    ],
    "tags": [
      "comfort",
      "breakfast",
      "batch-cook",
      "one-pot",
      "to-try"
    ],
    "allium_free": true,
    "source_url": null,
    "notes": "Draft, not cooked yet. Traditionally topped with spring onion, so leave that off. Watch jarred chilli crisp and chilli oil too: many contain fried onion, so read the label before topping with it. Thickens as it sits; loosen with water when reheating.",
    "rating": null,
    "last_cooked": null
  },
  {
    "title": "Red lentil, fennel and lemon soup",
    "servings": 4,
    "prep_minutes": 10,
    "cook_minutes": 35,
    "ingredients": [
      {
        "qty": "30",
        "unit": "ml",
        "item": "olive oil"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "fennel bulb, diced"
      },
      {
        "qty": "2",
        "unit": "",
        "item": "carrots, diced"
      },
      {
        "qty": "2",
        "unit": "",
        "item": "celery sticks, diced"
      },
      {
        "qty": "4",
        "unit": "",
        "item": "garlic cloves, chopped"
      },
      {
        "qty": "2",
        "unit": "tsp",
        "item": "ground cumin"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "ground coriander"
      },
      {
        "qty": "0.5",
        "unit": "tsp",
        "item": "ground turmeric"
      },
      {
        "qty": "250",
        "unit": "g",
        "item": "red lentils, rinsed"
      },
      {
        "qty": "1.2",
        "unit": "L",
        "item": "water"
      },
      {
        "qty": "15",
        "unit": "g",
        "item": "white miso paste"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "salt, plus more to taste"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "lemon, juiced"
      },
      {
        "qty": "",
        "unit": "",
        "item": "yoghurt, olive oil and fennel fronds, to serve"
      }
    ],
    "steps": [
      "Heat the oil in a large pot over medium. Add the fennel, carrot and celery and cook 10 minutes until soft.",
      "Add the garlic, cumin, coriander and turmeric and stir 1 minute.",
      "Add the lentils and water, bring to the boil and skim off any foam. Simmer 20 minutes, until the lentils collapse.",
      "Stir the miso into a ladle of the hot soup until dissolved, then return it to the pot with the salt and lemon juice. Blitz about half with a stick blender for body, leaving some texture.",
      "Taste and adjust the salt and lemon. Serve with a spoon of yoghurt, a drizzle of oil and the fennel fronds."
    ],
    "tags": [
      "soup",
      "vegetarian",
      "batch-cook",
      "freezer-friendly",
      "to-try"
    ],
    "allium_free": true,
    "source_url": null,
    "notes": "Draft, not cooked yet. The miso is doing the job stock would, which matters here because almost all commercial stock contains onion. Freezes well; add a splash of water when reheating.",
    "rating": null,
    "last_cooked": null
  },
  {
    "title": "Fish tacos with quick-pickled fennel slaw",
    "servings": 3,
    "prep_minutes": 20,
    "cook_minutes": 8,
    "ingredients": [
      {
        "qty": "400",
        "unit": "g",
        "item": "firm white fish fillets (flathead, whiting or Australian salmon)"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "ground cumin"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "smoked paprika"
      },
      {
        "qty": "0.5",
        "unit": "tsp",
        "item": "salt"
      },
      {
        "qty": "15",
        "unit": "ml",
        "item": "olive oil"
      },
      {
        "qty": "6",
        "unit": "small",
        "item": "corn or flour tortillas"
      },
      {
        "qty": "1",
        "unit": "small",
        "item": "fennel bulb, shaved paper-thin"
      },
      {
        "qty": "100",
        "unit": "g",
        "item": "red cabbage, finely shredded"
      },
      {
        "qty": "45",
        "unit": "ml",
        "item": "lime juice (about 2 limes)"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "sugar"
      },
      {
        "qty": "0.5",
        "unit": "tsp",
        "item": "salt (for the slaw)"
      },
      {
        "qty": "100",
        "unit": "g",
        "item": "Greek yoghurt"
      },
      {
        "qty": "15",
        "unit": "ml",
        "item": "lime juice (for the sauce)"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "avocado, sliced"
      },
      {
        "qty": "15",
        "unit": "g",
        "item": "coriander leaves"
      }
    ],
    "steps": [
      "Make the slaw: toss the fennel and cabbage with the lime juice, sugar and salt. Leave at least 20 minutes; it can sit up to 2 hours.",
      "Stir the yoghurt with the lime juice and a pinch of salt.",
      "Rub the fish with the cumin, paprika, salt and oil. Pan-fry over medium-high 2 to 3 minutes a side, until it just flakes, then break into chunks.",
      "Warm the tortillas in a dry pan for about 20 seconds a side.",
      "Build: yoghurt sauce, fish, slaw, avocado and coriander."
    ],
    "tags": [
      "fish",
      "tacos",
      "weeknight",
      "high-protein",
      "to-try"
    ],
    "allium_free": true,
    "source_url": null,
    "notes": "Draft, not cooked yet. Pickled fennel stands in for the usual quick-pickled red onion. Use the individual spices rather than a taco seasoning packet: those nearly always contain onion powder.",
    "rating": null,
    "last_cooked": null
  },
  {
    "title": "Lemon-oregano chicken souvlaki bowls",
    "servings": 4,
    "prep_minutes": 20,
    "cook_minutes": 15,
    "ingredients": [
      {
        "qty": "800",
        "unit": "g",
        "item": "chicken thigh fillets, cut into 3 cm pieces"
      },
      {
        "qty": "60",
        "unit": "ml",
        "item": "olive oil (marinade)"
      },
      {
        "qty": "60",
        "unit": "ml",
        "item": "lemon juice (marinade)"
      },
      {
        "qty": "4",
        "unit": "",
        "item": "garlic cloves, finely chopped (marinade)"
      },
      {
        "qty": "2",
        "unit": "tsp",
        "item": "dried oregano"
      },
      {
        "qty": "1",
        "unit": "tsp",
        "item": "salt"
      },
      {
        "qty": "",
        "unit": "",
        "item": "black pepper"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "Lebanese cucumber, grated and squeezed dry (tzatziki)"
      },
      {
        "qty": "250",
        "unit": "g",
        "item": "Greek yoghurt (tzatziki)"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "small garlic clove, grated (tzatziki)"
      },
      {
        "qty": "10",
        "unit": "ml",
        "item": "lemon juice (tzatziki)"
      },
      {
        "qty": "15",
        "unit": "ml",
        "item": "olive oil (tzatziki)"
      },
      {
        "qty": "2",
        "unit": "tbsp",
        "item": "chopped dill or mint (tzatziki)"
      },
      {
        "qty": "300",
        "unit": "g",
        "item": "tomatoes, cut into wedges"
      },
      {
        "qty": "1",
        "unit": "",
        "item": "Lebanese cucumber, sliced"
      },
      {
        "qty": "80",
        "unit": "g",
        "item": "feta"
      },
      {
        "qty": "80",
        "unit": "g",
        "item": "Kalamata olives"
      },
      {
        "qty": "4",
        "unit": "",
        "item": "pita breads, or 300 g cooked rice"
      }
    ],
    "steps": [
      "Mix the marinade ingredients, add the chicken and turn to coat. Marinate at least 2 hours, or overnight in the fridge.",
      "Make the tzatziki: stir everything together and season with salt. Keep it cold.",
      "Heat a large pan or grill over high heat. Cook the chicken in two batches, 3 to 4 minutes a side, until charred in spots and cooked through.",
      "Warm the pita or rice. Divide between bowls with the chicken, tomato, cucumber, feta and olives, and spoon over the tzatziki."
    ],
    "tags": [
      "chicken",
      "greek",
      "high-protein",
      "meal-prep",
      "family",
      "to-try"
    ],
    "allium_free": true,
    "source_url": null,
    "notes": "Draft, not cooked yet. Souvlaki is normally served with a red onion salad; skip it, the tomato and cucumber carry it. Threaded onto skewers it is the same recipe; soak wooden ones for 30 minutes. Cooked chicken keeps 3 days for lunches.",
    "rating": null,
    "last_cooked": null
  }
]
$seed$::jsonb) as r(
    title text, servings integer, prep_minutes integer, cook_minutes integer,
    ingredients jsonb, steps jsonb, tags jsonb, allium_free boolean,
    source_url text, notes text, rating smallint, last_cooked date
  )
  where not exists (
    select 1 from public.recipes e where e.user_id = owner_id and e.title = r.title
  );

  get diagnostics inserted = row_count;
  raise notice 'Inserted % of 12 recipes (the rest already existed).', inserted;
end
$seed_do$;
