#!/usr/bin/env node
/* Turns seed/recipes.json into supabase/seed.sql.

   Why SQL and not an in-app import: the site bundle is public, so anything compiled into
   it is readable by anyone. Recipes are not secrets, but the README's rule is that data
   lives behind Row Level Security and the bundle carries none. Pasting SQL into the
   Supabase editor keeps that rule intact.

   Usage:
     node scripts/build-seed.mjs            write supabase/seed.sql
     node scripts/build-seed.mjs --check    exit 1 if seed.sql is out of date

   Exits non-zero on anything that would make the insert fail, and on any recipe marked
   allium_free whose ingredients or method mention an allium. */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "seed", "recipes.json");
const OUT = join(root, "supabase", "seed.sql");

/* Onion, leek, shallot, chive and their relatives. Garlic is deliberately absent: it is
   not what the allergy is about (see supabase/schema.sql). Matched as whole words so "archive" is safe. */
const ALLIUM =
  /\b(onions?|leeks?|shallots?|eschalots?|chives?|scallions?|spring onions?|green onions?|ramps?|onion (?:powder|flakes))\b/i;

/* Packaged things that often hide onion. Not errors, because plenty are fine, but each one
   is worth a look at the label before cooking for someone with an allergy. */
const HIDDEN =
  /\b(stock|broth|bouillon|sausages?|chorizo|salami|worcestershire|curry (?:powder|paste)|taco seasoning|seasoning|spice (?:mix|blend)|ketchup|barbecue|bbq|hoisin|oyster sauce|chilli (?:crisp|oil)|pesto|gravy(?! beef)|stuffing)\b/i;

const errors = [];
const warnings = [];
const fail = (r, msg) => errors.push(`${r?.title ?? "?"}: ${msg}`);

const recipes = JSON.parse(readFileSync(SRC, "utf8"));
if (!Array.isArray(recipes) || recipes.length === 0) {
  console.error("seed/recipes.json must be a non-empty array");
  process.exit(1);
}

const intOrNull = (v) => v === null || (Number.isInteger(v) && v >= 0);
const titles = new Set();

for (const r of recipes) {
  if (typeof r.title !== "string" || r.title.trim() === "") fail(r, "title is empty");
  if (titles.has(r.title)) fail(r, "duplicate title (the seed matches on title to stay idempotent)");
  titles.add(r.title);

  if (!(r.servings === null || (Number.isInteger(r.servings) && r.servings > 0))) fail(r, "servings must be a positive integer or null");
  if (!intOrNull(r.prep_minutes)) fail(r, "prep_minutes must be a non-negative integer or null");
  if (!intOrNull(r.cook_minutes)) fail(r, "cook_minutes must be a non-negative integer or null");
  if (!(r.rating === null || (Number.isInteger(r.rating) && r.rating >= 1 && r.rating <= 5))) fail(r, "rating must be 1-5 or null");
  if (typeof r.allium_free !== "boolean") fail(r, "allium_free must be a boolean");

  if (!Array.isArray(r.ingredients) || r.ingredients.length === 0) fail(r, "no ingredients");
  for (const i of r.ingredients ?? []) {
    if (typeof i.item !== "string" || i.item.trim() === "") fail(r, "ingredient with empty item");
    for (const k of ["qty", "unit", "item"]) {
      if (typeof i[k] !== "string") fail(r, `ingredient "${i.item}" needs a string ${k}`);
    }
  }
  if (!Array.isArray(r.steps) || r.steps.length === 0) fail(r, "no steps");
  if (!Array.isArray(r.tags) || r.tags.some((t) => t !== t.toLowerCase().trim())) fail(r, "tags must be lowercase and trimmed (the form lowercases on save)");

  if (r.allium_free) {
    /* Ingredients and method only. Titles and notes are allowed to say "onion-free" or
       "leave off the spring onion", and a lint that fires on a warning label is noise. */
    const body = [...r.ingredients.map((i) => i.item), ...r.steps];
    for (const text of body) {
      const m = text.match(ALLIUM);
      if (m) fail(r, `marked allium_free but mentions "${m[0]}": ${text.slice(0, 70)}`);
    }
    for (const i of r.ingredients) {
      const m = i.item.match(HIDDEN);
      if (m) warnings.push(`${r.title}: "${m[0]}" in "${i.item}" often hides onion, check the label`);
    }
  }
}

if (errors.length) {
  console.error(`\n${errors.length} problem(s):\n`);
  for (const e of errors) console.error("  x " + e);
  process.exit(1);
}

/* The JSON goes into SQL inside a dollar-quoted string, so it must not contain the
   closing tag. Backslashes are literal inside dollar quotes, so JSON escapes survive. */
const TAG = "$seed$";
const json = JSON.stringify(recipes, null, 2);
if (json.includes(TAG)) {
  console.error(`seed/recipes.json contains ${TAG}, which would end the SQL string early`);
  process.exit(1);
}

const sql = `-- Starter recipes. GENERATED by scripts/build-seed.mjs from seed/recipes.json.
-- Edit the JSON and re-run the script; do not edit this file by hand.
--
-- HOW TO RUN: Supabase dashboard -> SQL Editor -> paste this whole file -> Run.
-- Run supabase/schema.sql first, and sign in to the app once so your account exists.
--
-- The SQL editor runs as a privileged role that bypasses Row Level Security, so this
-- script has to say whose recipes these are. Set owner_email to the address you signed
-- in with. It fails loudly if no such user exists rather than inserting orphan rows.
--
-- Safe to re-run: a recipe whose title you already have is skipped, not duplicated.

do $seed_do$
declare
  owner_email constant text := 'CHANGE-ME@example.com';
  owner_id    uuid;
  inserted    integer;
begin
  select id into owner_id from auth.users where lower(email) = lower(owner_email);
  if owner_id is null then
    raise exception 'No user with email %. Edit owner_email at the top of this script.', owner_email;
  end if;

  insert into public.recipes
    (user_id, title, servings, prep_minutes, cook_minutes, ingredients, steps, tags,
     allium_free, source_url, notes, rating, last_cooked)
  select
    owner_id, r.title, r.servings, r.prep_minutes, r.cook_minutes, r.ingredients,
    array(select jsonb_array_elements_text(r.steps)),
    array(select jsonb_array_elements_text(r.tags)),
    r.allium_free, r.source_url, r.notes, r.rating, r.last_cooked
  from jsonb_to_recordset(${TAG}
${json}
${TAG}::jsonb) as r(
    title text, servings integer, prep_minutes integer, cook_minutes integer,
    ingredients jsonb, steps jsonb, tags jsonb, allium_free boolean,
    source_url text, notes text, rating smallint, last_cooked date
  )
  where not exists (
    select 1 from public.recipes e where e.user_id = owner_id and e.title = r.title
  );

  get diagnostics inserted = row_count;
  raise notice 'Inserted % of ${recipes.length} recipes (the rest already existed).', inserted;
end
$seed_do$;
`;

for (const w of warnings) console.warn("  ! " + w);

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== sql) {
    console.error("supabase/seed.sql is out of date. Run: node scripts/build-seed.mjs");
    process.exit(1);
  }
  console.log(`seed.sql is up to date (${recipes.length} recipes).`);
} else {
  writeFileSync(OUT, sql);
  console.log(`Wrote supabase/seed.sql (${recipes.length} recipes, ${warnings.length} label warnings).`);
}
